// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_comerce_api.models;

#nullable disable

namespace e_comerce_api.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20251210160814_hgshshshs")]
    partial class hgshshshs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("e_comerce_api.models.Affiliate", b =>
                {
                    b.Property<int>("AffiliateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AffiliateId"));

                    b.Property<string>("AffiliateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AvailableBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CommissionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TotalEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("WithdrawnAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AffiliateId");

                    b.HasIndex("UserId");

                    b.ToTable("Affiliates");
                });

            modelBuilder.Entity("e_comerce_api.models.AffiliateComession", b =>
                {
                    b.Property<int>("CommissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommissionId"));

                    b.Property<int>("AffiliateId")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("OrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Sellerid")
                        .HasColumnType("int");

                    b.HasKey("CommissionId");

                    b.HasIndex("AffiliateId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sellerid");

                    b.ToTable("AffiliateComession");
                });

            modelBuilder.Entity("e_comerce_api.models.AffiliateSellerRelationship", b =>
                {
                    b.Property<int>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelationshipId"));

                    b.Property<int>("AffiliateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CommissionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RelationshipId");

                    b.HasIndex("AffiliateId");

                    b.HasIndex("SellerId");

                    b.ToTable("AffiliateSellerRelationships");
                });

            modelBuilder.Entity("e_comerce_api.models.AffiliateWithDrawel", b =>
                {
                    b.Property<int>("WithdrawalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WithdrawalId"));

                    b.Property<int>("AffiliateId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WithdrawalId");

                    b.HasIndex("AffiliateId");

                    b.ToTable("AffiliateWithDrawel");
                });

            modelBuilder.Entity("e_comerce_api.models.Cart", b =>
                {
                    b.Property<int>("Cartid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cartid"));

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("customer_id")
                        .HasColumnType("int");

                    b.Property<int>("statue")
                        .HasColumnType("int");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Cartid");

                    b.HasIndex("customer_id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("e_comerce_api.models.CartItems", b =>
                {
                    b.Property<int>("CartItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemsId"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtAddition")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("CartItemsId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("e_comerce_api.models.Copons", b =>
                {
                    b.Property<int>("CoponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoponId"));

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinimumPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsageCount")
                        .HasColumnType("int");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("decription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("startAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CoponId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("e_comerce_api.models.HelpfulRating", b =>
                {
                    b.Property<int>("HelpfulId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HelpfulId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHelpful")
                        .HasColumnType("bit");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.HasKey("HelpfulId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RatingId");

                    b.ToTable("HelpfulRatings");
                });

            modelBuilder.Entity("e_comerce_api.models.OrderItems", b =>
                {
                    b.Property<int>("OrderItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemsId"));

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int?>("sub_order_id")
                        .HasColumnType("int");

                    b.Property<int?>("variant_id")
                        .HasColumnType("int");

                    b.HasKey("OrderItemsId");

                    b.HasIndex("product_id");

                    b.HasIndex("sub_order_id");

                    b.HasIndex("variant_id");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("e_comerce_api.models.ProductAttributies", b =>
                {
                    b.Property<int>("ProductAttriid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductAttriid"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFilterable")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("PossibleValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("subcatid")
                        .HasColumnType("int");

                    b.HasKey("ProductAttriid");

                    b.HasIndex("subcatid");

                    b.ToTable("ProductAttributies");
                });

            modelBuilder.Entity("e_comerce_api.models.ProductAttributiesValue", b =>
                {
                    b.Property<int>("ProductAttrValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductAttrValueId"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductAttrValueId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttributeValues");
                });

            modelBuilder.Entity("e_comerce_api.models.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("e_comerce_api.models.Rating", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateId"));

                    b.Property<int?>("HelpfulCount")
                        .HasColumnType("int");

                    b.Property<bool?>("IsVerifiedPurchase")
                        .HasColumnType("bit");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("customerid")
                        .HasColumnType("int");

                    b.Property<int>("productid")
                        .HasColumnType("int");

                    b.Property<int>("rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RateId");

                    b.HasIndex("customerid");

                    b.HasIndex("productid");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("e_comerce_api.models.ReviewImage", b =>
                {
                    b.Property<int>("ReviewImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.HasKey("ReviewImageId");

                    b.HasIndex("RatingId");

                    b.ToTable("ReviewImages");
                });

            modelBuilder.Entity("e_comerce_api.models.SubCategory", b =>
                {
                    b.Property<int>("SbuCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SbuCatId"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("cat_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SbuCatId");

                    b.HasIndex("cat_id");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("e_comerce_api.models.SubOrder", b =>
                {
                    b.Property<int>("SubOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubOrderId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("seller_id")
                        .HasColumnType("int");

                    b.HasKey("SubOrderId");

                    b.HasIndex("OrderId");

                    b.HasIndex("seller_id");

                    b.ToTable("SubOrders");
                });

            modelBuilder.Entity("e_comerce_api.models.UserCopon", b =>
                {
                    b.Property<int>("UserCoponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserCoponId"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("copon_id")
                        .HasColumnType("int");

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.HasKey("UserCoponId");

                    b.HasIndex("copon_id");

                    b.HasIndex("customer_id");

                    b.ToTable("UserCoupons");
                });

            modelBuilder.Entity("e_comerce_api.models.WishList", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("WishlistId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("e_comerce_api.models.WithItems", b =>
                {
                    b.Property<int>("WishlistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistItemId"));

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("WishlistItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("e_comerce_api.models.address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("e_comerce_api.models.admin", b =>
                {
                    b.Property<int>("Adminid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Adminid"));

                    b.Property<string>("permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Adminid");

                    b.HasIndex("user_id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("e_comerce_api.models.applicationuser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("lastlogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("e_comerce_api.models.category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("e_comerce_api.models.customer", b =>
                {
                    b.Property<int>("Customerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Customerid"));

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Customerid");

                    b.HasIndex("user_id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("e_comerce_api.models.order", b =>
                {
                    b.Property<int>("Orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Orderid"));

                    b.Property<string>("AffiliateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AffiliateId")
                        .HasColumnType("int");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("address_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("customer_id")
                        .HasColumnType("int");

                    b.Property<string>("statue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Orderid");

                    b.HasIndex("AffiliateId");

                    b.HasIndex("CouponId");

                    b.HasIndex("address_id");

                    b.HasIndex("customer_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("e_comerce_api.models.product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<double>("AverageRate")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Mainimageurl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("basicprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("discountpercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isaveliable")
                        .HasColumnType("bit");

                    b.Property<int?>("seller_id")
                        .HasColumnType("int");

                    b.Property<int>("stockquantity")
                        .HasColumnType("int");

                    b.Property<int?>("sub_cat_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("seller_id");

                    b.HasIndex("sub_cat_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("e_comerce_api.models.productVariant", b =>
                {
                    b.Property<int>("ProductVariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductVariantId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Mainimageurl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("basicprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("discountpercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("isaveliable")
                        .HasColumnType("bit");

                    b.Property<bool?>("isdefault")
                        .HasColumnType("bit");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("stockquantity")
                        .HasColumnType("int");

                    b.HasKey("ProductVariantId");

                    b.HasIndex("product_id");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("e_comerce_api.models.productVariantAttribute", b =>
                {
                    b.Property<int>("ProductVariantAttrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductVariantAttrid"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("possiblevalue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("variatn_id")
                        .HasColumnType("int");

                    b.HasKey("ProductVariantAttrid");

                    b.HasIndex("variatn_id");

                    b.ToTable("VariantAttributes");
                });

            modelBuilder.Entity("e_comerce_api.models.productview", b =>
                {
                    b.Property<int>("ProductViewid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductViewid"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductViewid");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductViews");
                });

            modelBuilder.Entity("e_comerce_api.models.seller", b =>
                {
                    b.Property<int>("Sellerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sellerid"));

                    b.Property<string>("CustomerServicesPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("businessDesription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("businessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_verfied")
                        .HasColumnType("bit");

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("rate")
                        .HasColumnType("real");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("verfiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Sellerid");

                    b.HasIndex("user_id");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("e_comerce_api.models.applicationuser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("e_comerce_api.models.applicationuser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comerce_api.models.applicationuser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("e_comerce_api.models.applicationuser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("e_comerce_api.models.Affiliate", b =>
                {
                    b.HasOne("e_comerce_api.models.applicationuser", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("e_comerce_api.models.AffiliateComession", b =>
                {
                    b.HasOne("e_comerce_api.models.Affiliate", "Affiliate")
                        .WithMany("affiliateComessions")
                        .HasForeignKey("AffiliateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comerce_api.models.order", "order")
                        .WithMany("AffiliateCommissions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comerce_api.models.product", null)
                        .WithMany("AffiliateCommissions")
                        .HasForeignKey("ProductId");

                    b.HasOne("e_comerce_api.models.seller", null)
                        .WithMany("AffiliateCommissions")
                        .HasForeignKey("Sellerid");

                    b.Navigation("Affiliate");

                    b.Navigation("order");
                });

            modelBuilder.Entity("e_comerce_api.models.AffiliateSellerRelationship", b =>
                {
                    b.HasOne("e_comerce_api.models.Affiliate", "Affiliate")
                        .WithMany("affiliateSellerRelationships")
                        .HasForeignKey("AffiliateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comerce_api.models.seller", "Seller")
                        .WithMany("AffiliateSellerRelationships")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affiliate");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("e_comerce_api.models.AffiliateWithDrawel", b =>
                {
                    b.HasOne("e_comerce_api.models.Affiliate", "Affiliate")
                        .WithMany("affiliateWithdrawel")
                        .HasForeignKey("AffiliateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affiliate");
                });

            modelBuilder.Entity("e_comerce_api.models.Cart", b =>
                {
                    b.HasOne("e_comerce_api.models.customer", "customer")
                        .WithMany("Carts")
                        .HasForeignKey("customer_id");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("e_comerce_api.models.CartItems", b =>
                {
                    b.HasOne("e_comerce_api.models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("e_comerce_api.models.product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId");

                    b.HasOne("e_comerce_api.models.productVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId");

                    b.Navigation("Cart");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("e_comerce_api.models.HelpfulRating", b =>
                {
                    b.HasOne("e_comerce_api.models.customer", "Customer")
                        .WithMany("HelpfulRatings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comerce_api.models.Rating", "Rating")
                        .WithMany("helpfulRating")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("e_comerce_api.models.OrderItems", b =>
                {
                    b.HasOne("e_comerce_api.models.product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("product_id");

                    b.HasOne("e_comerce_api.models.SubOrder", "SubOrder")
                        .WithMany("Items")
                        .HasForeignKey("sub_order_id");

                    b.HasOne("e_comerce_api.models.productVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("variant_id");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");

                    b.Navigation("SubOrder");
                });

            modelBuilder.Entity("e_comerce_api.models.ProductAttributies", b =>
                {
                    b.HasOne("e_comerce_api.models.SubCategory", "SubCategory")
                        .WithMany("ProductAttributies")
                        .HasForeignKey("subcatid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("e_comerce_api.models.ProductAttributiesValue", b =>
                {
                    b.HasOne("e_comerce_api.models.ProductAttributies", "Attribute")
                        .WithMany("productAttributiesValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comerce_api.models.product", "Product")
                        .WithMany("ProductAttributeValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("e_comerce_api.models.ProductImage", b =>
                {
                    b.HasOne("e_comerce_api.models.product", "Product")
                        .WithMany("ProductImage")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("e_comerce_api.models.Rating", b =>
                {
                    b.HasOne("e_comerce_api.models.customer", "customer")
                        .WithMany("Ratings")
                        .HasForeignKey("customerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comerce_api.models.product", "product")
                        .WithMany("ratings")
                        .HasForeignKey("productid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("product");
                });

            modelBuilder.Entity("e_comerce_api.models.ReviewImage", b =>
                {
                    b.HasOne("e_comerce_api.models.Rating", "Rating")
                        .WithMany("reviewImages")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("e_comerce_api.models.SubCategory", b =>
                {
                    b.HasOne("e_comerce_api.models.category", "category")
                        .WithMany("subCategories")
                        .HasForeignKey("cat_id");

                    b.Navigation("category");
                });

            modelBuilder.Entity("e_comerce_api.models.SubOrder", b =>
                {
                    b.HasOne("e_comerce_api.models.order", "order")
                        .WithMany("SubOrders")
                        .HasForeignKey("OrderId");

                    b.HasOne("e_comerce_api.models.seller", "seller")
                        .WithMany("SubOrders")
                        .HasForeignKey("seller_id");

                    b.Navigation("order");

                    b.Navigation("seller");
                });

            modelBuilder.Entity("e_comerce_api.models.UserCopon", b =>
                {
                    b.HasOne("e_comerce_api.models.Copons", "copon")
                        .WithMany("users")
                        .HasForeignKey("copon_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comerce_api.models.customer", "customer")
                        .WithMany("UserCoupons")
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("copon");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("e_comerce_api.models.WishList", b =>
                {
                    b.HasOne("e_comerce_api.models.customer", "Customer")
                        .WithMany("Wishlists")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("e_comerce_api.models.WithItems", b =>
                {
                    b.HasOne("e_comerce_api.models.product", "Product")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_comerce_api.models.WishList", "Wishlist")
                        .WithMany("WishlistItems")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("e_comerce_api.models.address", b =>
                {
                    b.HasOne("e_comerce_api.models.applicationuser", "user")
                        .WithMany("addresses")
                        .HasForeignKey("UserId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("e_comerce_api.models.admin", b =>
                {
                    b.HasOne("e_comerce_api.models.applicationuser", "user")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("user");
                });

            modelBuilder.Entity("e_comerce_api.models.customer", b =>
                {
                    b.HasOne("e_comerce_api.models.applicationuser", "user")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("user");
                });

            modelBuilder.Entity("e_comerce_api.models.order", b =>
                {
                    b.HasOne("e_comerce_api.models.Affiliate", "Affiliate")
                        .WithMany("orders")
                        .HasForeignKey("AffiliateId");

                    b.HasOne("e_comerce_api.models.Copons", "Coupon")
                        .WithMany("orders")
                        .HasForeignKey("CouponId");

                    b.HasOne("e_comerce_api.models.address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("address_id");

                    b.HasOne("e_comerce_api.models.customer", "customer")
                        .WithMany("orders")
                        .HasForeignKey("customer_id");

                    b.Navigation("Address");

                    b.Navigation("Affiliate");

                    b.Navigation("Coupon");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("e_comerce_api.models.product", b =>
                {
                    b.HasOne("e_comerce_api.models.seller", "seller")
                        .WithMany("Products")
                        .HasForeignKey("seller_id");

                    b.HasOne("e_comerce_api.models.SubCategory", "subcategory")
                        .WithMany("products")
                        .HasForeignKey("sub_cat_id");

                    b.Navigation("seller");

                    b.Navigation("subcategory");
                });

            modelBuilder.Entity("e_comerce_api.models.productVariant", b =>
                {
                    b.HasOne("e_comerce_api.models.product", "product")
                        .WithMany("productVariants")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("e_comerce_api.models.productVariantAttribute", b =>
                {
                    b.HasOne("e_comerce_api.models.productVariant", "productVariant")
                        .WithMany("attributes")
                        .HasForeignKey("variatn_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("productVariant");
                });

            modelBuilder.Entity("e_comerce_api.models.productview", b =>
                {
                    b.HasOne("e_comerce_api.models.customer", "Customer")
                        .WithMany("ProductViews")
                        .HasForeignKey("CustomerId");

                    b.HasOne("e_comerce_api.models.product", "Product")
                        .WithMany("ProductViews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("e_comerce_api.models.seller", b =>
                {
                    b.HasOne("e_comerce_api.models.applicationuser", "user")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("user");
                });

            modelBuilder.Entity("e_comerce_api.models.Affiliate", b =>
                {
                    b.Navigation("affiliateComessions");

                    b.Navigation("affiliateSellerRelationships");

                    b.Navigation("affiliateWithdrawel");

                    b.Navigation("orders");
                });

            modelBuilder.Entity("e_comerce_api.models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("e_comerce_api.models.Copons", b =>
                {
                    b.Navigation("orders");

                    b.Navigation("users");
                });

            modelBuilder.Entity("e_comerce_api.models.ProductAttributies", b =>
                {
                    b.Navigation("productAttributiesValues");
                });

            modelBuilder.Entity("e_comerce_api.models.Rating", b =>
                {
                    b.Navigation("helpfulRating");

                    b.Navigation("reviewImages");
                });

            modelBuilder.Entity("e_comerce_api.models.SubCategory", b =>
                {
                    b.Navigation("ProductAttributies");

                    b.Navigation("products");
                });

            modelBuilder.Entity("e_comerce_api.models.SubOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("e_comerce_api.models.WishList", b =>
                {
                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("e_comerce_api.models.address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("e_comerce_api.models.applicationuser", b =>
                {
                    b.Navigation("addresses");
                });

            modelBuilder.Entity("e_comerce_api.models.category", b =>
                {
                    b.Navigation("subCategories");
                });

            modelBuilder.Entity("e_comerce_api.models.customer", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("HelpfulRatings");

                    b.Navigation("ProductViews");

                    b.Navigation("Ratings");

                    b.Navigation("UserCoupons");

                    b.Navigation("Wishlists");

                    b.Navigation("orders");
                });

            modelBuilder.Entity("e_comerce_api.models.order", b =>
                {
                    b.Navigation("AffiliateCommissions");

                    b.Navigation("SubOrders");
                });

            modelBuilder.Entity("e_comerce_api.models.product", b =>
                {
                    b.Navigation("AffiliateCommissions");

                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductAttributeValues");

                    b.Navigation("ProductImage");

                    b.Navigation("ProductViews");

                    b.Navigation("WishlistItems");

                    b.Navigation("productVariants");

                    b.Navigation("ratings");
                });

            modelBuilder.Entity("e_comerce_api.models.productVariant", b =>
                {
                    b.Navigation("attributes");
                });

            modelBuilder.Entity("e_comerce_api.models.seller", b =>
                {
                    b.Navigation("AffiliateCommissions");

                    b.Navigation("AffiliateSellerRelationships");

                    b.Navigation("Products");

                    b.Navigation("SubOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
